name: Build and Push to Docker Hub

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # FRONTEND
      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/products-frontend:latest ./client

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/products-frontend:latest

      # BACKEND
      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/products-backend:latest ./server

      - name: 🚚 Push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/products-backend:latest
      
      # EMAIL
      - name: Send email notification
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Build & Deployment - ${{ github.repository }}
          to: ${{ github.event.head_commit.author.email }}
          from: ${{ secrets.MAIL_USERNAME }}
          html_body: true
          body: |
            ✅ <b>Build & Push Completed!</b><br>
            Repo: <a href="https://github.com/${{ github.repository }}">{{ github.repository }}</a><br>
            Commit: ${{ github.sha }}<br>
            Branch: ${{ github.ref_name }}<br>
            Status: <b>${{ job.status }}</b><br><br>
            ⏱ Run Time: ${{ github.run_id }}<br>
      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Backend Deploy
      - name: Restart Azure Backend
        run: |
          az webapp restart --name ${{ secrets.AZURE_BACKEND_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

      # Frontend Deploy
      - name: Restart Azure Frontend
        run: |
          az webapp restart --name ${{ secrets.AZURE_FRONTENT_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
      # EMAIL
      - name: Send email notification
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Build & Deployment - ${{ github.repository }}
          to: ${{ github.event.head_commit.author.email }}
          from: ${{ secrets.MAIL_USERNAME }}
          html_body: true
          body: |
            ✅ <b>Deploy Completed!</b><br>
            Repo: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a><br>
            Commit: ${{ github.sha }}<br>
            Branch: ${{ github.ref_name }}<br>
            🌐 GitHub Actions workflow zakończony sukcesem.